version: '3'

services:
  frontend:
    image: ehmeeudosen/frontend-chaos:${GIT_COMMIT_HASH}
    ports:
      - "80:80"

  backend:
    image: ehmeeudosen/backend-chaos:${GIT_COMMIT_HASH}
    ports:
      - "5000:5000"