version: '3'

services:
  frontend:
    build: ./frontend
#    image: ehmeeudosen/frontend-chaos:${GIT_COMMIT_HASH}
    ports:
      - "3000:80"

  backend:
    build: ./backend
#    image: ehmeeudosen/backend-chaos:${GIT_COMMIT_HASH}
    ports:
      - "5000:5000"
