name: CI/CD for React + Flask + Docker

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e  # Exit if any command fails
            cd /home/ubuntu/workspace/very-chaotic
            # Pull the latest changes from GitHub
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d
            # Clean up old, unused Docker images
            docker image prune -f
